DATE_INPUT_FORMAT = "%d.%m.%Y"
DATE_DISPLAY_FORMAT = "%d.%m.%Y"

MSG_EMPTY_TITLE = "Ошибка: Название не должно быть пустым"
MSG_INVALID_DATE = "Ошибка: Неверный формат даты! Используйте дд.мм.гггг"
MSG_TASK_ADDED = "Задача '{title}' успешно добавлена."
MSG_TASK_REMOVED = "Задача '{title}' удалена."
MSG_TASK_NOT_FOUND = "Ошибка: Задача не найдена."
MSG_LIST_EMPTY = "Список задач пуст."
MSG_INVALID_CHOICE = "Ошибка: Выберите действие от 1 до 5."
MSG_EXIT = "До свидания."
MSG_INVALID_STATUS = "Ошибка: Неверный номер статуса."
MSG_INVALID_TASK_NUMBER = "Ошибка: Неверный номер задачи."
MSG_NO_OVERDUE = "Нет просроченных задач."
